name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O tu rama principal

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v5  # ¡Actualizado!

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # ¡Actualizado!
        with:
          path: .  # Cambia si tus archivos están en otra carpeta (como ./docs)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # ¡Actualizado!
