name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # o la rama que estés usando

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Dummy artifact upload setup (prevent error)
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: ./non-existent-folder
          if-no-files-found: ignore

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # o "public", "dist", etc. si usas una carpeta específica

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
